# Generated by Django 5.2 on 2025-07-07 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=120)),
                ('body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('up_votes', models.PositiveIntegerField(db_index=True, default=0)),
                ('down_votes', models.PositiveIntegerField(default=0)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='post', to='communities.community')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', related_query_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
                'indexes': [models.Index(fields=['community', '-created_at'], name='post_communi_3553f0_idx'), models.Index(fields=['user', '-created_at'], name='post_user_id_52de59_idx'), models.Index(fields=['-up_votes', '-created_at'], name='post_up_vote_a6cdd5_idx')],
            },
        ),
    ]
