# Generated by Django 5.2 on 2026-02-15 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')], help_text='The vote value: +1 for upvote, -1 for downvote.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the vote was created.')),
                ('post', models.ForeignKey(help_text='The post being voted on.', on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', related_query_name='post_vote', to='posts.post')),
                ('user', models.ForeignKey(help_text='The user who cast the vote.', on_delete=django.db.models.deletion.CASCADE, related_name='post_votes', related_query_name='post_vote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Vote',
                'verbose_name_plural': 'Post Votes',
                'db_table': 'post_vote',
                'indexes': [models.Index(fields=['post'], name='post_vote_post_id_58a9ef_idx'), models.Index(fields=['user'], name='post_vote_user_id_8a4025_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
