# Generated by Django 5.2 on 2025-08-11 15:58

import django.core.validators
import django.db.models.deletion
import users.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', help_text='Site theme preferences.', max_length=20, verbose_name='theme')),
                ('language', models.CharField(choices=[('en-us', 'English (US)')], default='en-us', help_text='Preferred language.', max_length=20, verbose_name='language')),
                ('show_online_status', models.BooleanField(default=True, help_text="Show when you're online to other users.", verbose_name='show_online_status')),
                ('show_email', models.BooleanField(default=False, help_text="Show when you're online to other users.", verbose_name='show email')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'user preferences',
                'verbose_name_plural': 'user preferences',
                'db_table': 'user_preferences',
            },
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Your preferred display name (optional).', max_length=30, verbose_name='display_name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(blank=True, help_text='Your GitHub username (optional).', max_length=50, verbose_name='GitHub username'),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Your LinkedIn username (optional).', max_length=50, verbose_name='LinkedIn username'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text="Where you're based (optional).", max_length=100, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(blank=True, help_text='Your website or blog (optional).', verbose_name='website'),
        ),
        migrations.AddField(
            model_name='profile',
            name='x',
            field=models.CharField(blank=True, help_text='Your X username (optional).', max_length=50, verbose_name='X username'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the verification email was last sent.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token for email verification.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user has verified their email address.', verbose_name='email verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, help_text='When the user was last active on the site.', null=True, verbose_name='last active'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (max 2MB, square image recommended).', null=True, upload_to=users.utils.user_avatar_path, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Tell us about yourself (max 500 characters).', max_length=500, validators=[django.core.validators.MaxLengthValidator(500, 'The Bio cannot be longer than 500 characters.')], verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Enter a valid email address.', 'unique': 'A user with that email already exists.'}, help_text='Required. Your email address will be verified.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 3-30 characters. Letters, numbers and underscores.', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='Username can only contain letters, numbers and underscores.', regex='^[a-zA-z0-9_]+$')], verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='user_usernam_b79065_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_active'], name='user_last_ac_d3d8d0_idx'),
        ),
    ]
