# Generated by Django 5.2 on 2025-12-25 15:52

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpreferences_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Enter a valid email address.', 'unique': 'A user with that email already exists.'}, help_text='Required. Your email address will be verified.', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[users.validators.UserPasswordValidator()], verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 3-30 characters. Letters, numbers and underscores.', max_length=30, unique=True, validators=[users.validators.UserUsernameValidator()], verbose_name='username'),
        ),
    ]
