# Generated by Django 5.2 on 2025-12-30 11:05

import communities.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_community_options_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a community avatar (max 2MB, square image recommended).', null=True, upload_to=communities.utils.community_avatar_path, verbose_name='avatar'),
        ),
    ]
