name: Python Linting

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Install dependencies
      run: uv sync

    - name: Run ruff linter
      run: uv run ruff check .

    - name: Run ruff formatter check
      run: uv run ruff format --check .
